version: '3'

networks:
  cf_network:
    driver: bridge
    ipam:
     config:
       - subnet: 10.6.0.0/16

services:
  db:
    container_name: cf_db
    image: mariadb:10.1
    ports:
      - "38306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=roots3cr3t
        - MYSQL_DATABASE=cidadaofiscal
        - MYSQL_USER=cfuser
        - MYSQL_PASSWORD=cfs3cr3t
    volumes: 
      - ./etc/mysql:/docker-entrypoint-initdb.d
    networks:
      cf_network:
        ipv4_address: 10.6.0.5
  www:
    container_name: cf_www
    build: 
      context: .
      dockerfile: ./etc/docker/dockerfile_php_7
    volumes:
      - ../dist:/var/www/html
      - ./etc/php:/usr/local/etc/php
      - ./etc/apache2/apache2.conf:/etc/apache2/conf-enabled/apache2.conf
      - ./etc/apache2/hosts.conf:/etc/apache2/sites-enabled/hosts.conf
    ports:
      - "38080:80"
    links:
      - db
    networks:
      cf_network:
        ipv4_address: 10.6.0.6

